### ISSUE TITLE
[Bug] Indicators gone/in new line

### ISSUE THREAD

**Issue by Cyenia** [Puyodead1/replugged-platformindicators#12]
The indicators are gone in the members list of the server and in dms they are each in a new line.
I got my new "super fancy" username yesterday without the "#0000" and since then the problem is there

Stable 203239 (8685a47)
Host 1.0.9013 (32266)
Windows 10 64-Bit (10.0.22621)
Replugged v4.3.0

![image](https://github.com/Puyodead1/replugged-platformindicators/assets/35280763/cc2a1aba-438e-4a12-9780-416b28ed7355)
[discord.com-1686125862160.log](https://github.com/Puyodead1/replugged-platformindicators/files/11674463/discord.com-1686125862160.log)

**Comment by Puyodead1** [comment]
This should be fixed in v1.0.23
