### ISSUE TITLE
Error: waitForModule timed out after 10000ms

### ISSUE THREAD

**Issue by kittibyte** [Puyodead1/replugged-platformindicators#5]
running latest canary with the latest release of this plugin with the latest commit of replugged.
plugin does not seem to load anymore
![image](https://user-images.githubusercontent.com/35849198/220721895-36c139fe-ce40-4a0c-900a-ee5ae55a64d2.png)

**Comment by Puyodead1** [comment]
fixed in c12cd1b9d27522049b95003e2b59fa85132ae9a2 (v1.0.0-beta11)
