### ISSUE TITLE
really noticeable lag issues when using platform indicators

### ISSUE THREAD

**Issue by kittibyte** [Puyodead1/replugged-platformindicators#7]
without using platform indicators, scrolling through a chat in discord works as well as its supposed to be.
https://user-images.githubusercontent.com/35849198/226184408-25416580-b0a6-483f-8c13-8d6514bd0ec0.mp4

however, with platform indicators on, scrolling becomes extremely laggy for me, sometimes straight up just freezing a bunch.
https://user-images.githubusercontent.com/35849198/226184466-8f0eb4ab-1281-4af7-8473-928861769cc8.mp4

this same issue also seems to happen with the server list and the settings tab half of the time either takes really long to load or just refuses to load entirely.

this only seems to be caused by platform indicators and even disabling all my other plugins still causes this issue, so this is not a case of another plugin interfering with platform indicators

**Comment by Puyodead1** [comment]
what version of the plugin are you using?

**Comment by kittibyte** [comment]
whatever was the latest at the time i wrote this

**Comment by Puyodead1** [comment]
well that's not helpful. I've had people say they were using the latest version but they were actually not. There was a fix for a memory leak recently which is why I asked.

**Comment by kittibyte** [comment]
i checked again, the latest i had installed was v1.0.18 which is the memory leak fix wasnt it?

**Comment by Puyodead1** [comment]
I pushed version 1.20, try that

**Comment by kittibyte** [comment]
just compiled the latest source and that fixed all of the lag issues

**Comment by Puyodead1** [comment]
Sorry, I didn't realize until now that the release action was still broken.
