### ISSUE TITLE
message reactions are partially broken

### ISSUE THREAD

**Issue by kittibyte** [Puyodead1/replugged-platformindicators#8]
i mentioned this in the replugged discord server already but i am also opening up an issues for it just as a reminder.
trying to press on a already existing reaction on a message just does not do anything with platform indicators on.
https://user-images.githubusercontent.com/35849198/226185186-74b2c000-6462-4f4d-b601-af14dad5035d.mp4

you can still add reactions using the "add reaction" button instead which is why i say they are partially broken

**Comment by cool-aid-man** [comment]
Yes! It still has the issue.
Where you can't react to an `existing reaction` or **unreact** from any previously `reacted` msg.

**Comment by SamboyCoding** [comment]
In addition to this, the tooltip for hovering over a reaction also does not show up when Platform Indicators is enabled and discord is restarted.

**Comment by Puyodead1** [comment]
Can you give this a try? It seems to work fine with reactions. (zipped because github didn't like the file extension)
[me.puyodead1.PlatformIndicators.zip](https://github.com/Puyodead1/replugged-platformindicators/files/11101828/me.puyodead1.PlatformIndicators.zip)

**Comment by SamboyCoding** [comment]
Nope, makes no difference. Still no tooltips or ability to click reactions, and no error in the console either.

**Comment by Puyodead1** [comment]
I pushed version 1.20, try that

**Comment by cool-aid-man** [comment]
> I pushed version 1.20, try that

Hi!
just updated and Still no.

**Comment by kittibyte** [comment]
just compiled the latest version of the source code and message reaction seem to be fixed for me

**Comment by Puyodead1** [comment]
> > I pushed version 1.20, try that
> 
> Hi! just updated and Still no.

Sorry, I didn't realize until now that the release action was still broken. version 1.0.20 is released and should now show up in the updater
